export * from './types.js';
export {
  INK_COLORS,
  INK_HEX,
  inkHex,
  isMarkShape,
  MARK_SHAPES,
  MARK_SHAPE_LABELS,
  type InkColor,
  type MarkShape,
} from './ink.js';
export {
  createSessionClient,
  joinSession,
  JoinError,
  type FetchLike,
  type JoinSessionOptions,
  type WebSocketLike,
  type WebSocketCtor,
  type SessionClient,
  type SessionClientOptions,
} from './client.js';
export {
  createTagsClient,
  TagError,
  TAG_MAX_LENGTH,
  MAX_TAGS_PER_ITEM,
  TAGGABLE_ITEM_TYPES,
  type TaggableItemType,
  type SpaceTagFacet,
  type ItemTagSet,
  type TagsClient,
  type TagsClientOptions,
} from './tags.js';
export {
  createDeckClient,
  DeckError,
  DeckConflictError,
  type AssetsApi,
  type AssetUploadOptions,
  type DeckClient,
  type DeckClientOptions,
  type ConditionalDeckDetail,
  type DeckDetail,
  type DeckFileLink,
  type DeckFileLocation,
  type DeckFileLocationInput,
  type DeckFileSyncInput,
  type DeckDraft,
  type DeckDraftSaved,
  type DeckSaveResult,
  type DecksApi,
  type DeckStartOptions,
  type DeckStartResult,
  type DeckSummary,
  type DeckVersionSummary,
  type MediaAsset,
} from './decks.js';
export {
  createPrefsClient,
  PrefsError,
  MAX_PREFS_BYTES,
  MAX_PINS,
  PIN_KINDS,
  type PinKind,
  type PinnedItem,
  type UserPrefs,
  type PrefsClient,
  type PrefsClientOptions,
} from './prefs.js';
