import { VOICE_RETENTION_DAYS } from '@openroom/schema';

export type LearnerLocale = 'en' | 'fr' | 'de';
export const learnerLanguageNames: Record<LearnerLocale, string> = { en: 'English', fr: 'Français', de: 'Deutsch' };

const en = {
  interfaceLanguage: 'Interface language', close: 'Close',
  deadLink: 'This link no longer works', newLink: 'A new link comes from the tutor.',
  tooManyAttempts: 'Too many attempts',
  rateLimit: 'Too many tries from this connection in a short time. Reload after one minute — the link itself stays valid.',
  rateLimitShort: 'Too many attempts from your connection. Wait a minute, then reload this page.',
  loading: 'Loading…', learning: 'Learning', lesson: 'Lesson', practice: 'Practice', feedback: 'Feedback',
  lessonsError: 'Your sessions could not be loaded just now. Try again in a moment.',
  lessonEmpty: 'Your lesson appears here when your tutor shares it.', earlierSessions: 'Earlier sessions',
  loadingPractice: 'Loading practice…', practiceLoadError: 'Practice could not be loaded. Try reloading in a moment.',
  practiceDone: 'Your practice is done for now. Return later to practise again.', revisit: 'Revisit exercises',
  loadingFeedback: 'Loading feedback…', feedbackLoadError: 'Feedback could not be loaded. Try reloading in a moment.',
  feedbackEmpty: 'Your tutor’s feedback will appear here.', yourWords: 'Your words', tryThis: 'Try this', yourResponse: 'Your response',
  personalLink: 'Personal link — not for sharing. A lost link is replaced by the tutor.',
  thisSession: 'This session', nothingWritten: 'Nothing written up yet.', outcomes: 'Outcomes', materials: 'Materials',
  reading: 'Reading', writing: 'Writing', quiz: 'Quiz',
  saved: 'Saved', saving: 'Saving…', save: 'Save',
  writingChanged: 'The task has changed. Copy your writing before reloading to see the revised task.',
  writingError: 'Your writing could not be saved. Keep this page open and try again.',
  yourAnswer: 'Your answer', chooseAll: 'Choose all that apply.',
  gap: (number: number) => `Gap ${number}`, match: (label: string) => `Match ${label}`, chooseMatch: 'Choose a match',
  moveUp: (label: string) => `Move ${label} up`, moveDown: (label: string) => `Move ${label} down`,
  check: 'Check', correct: 'Correct.', compare: 'Compare your answer.', selfCheck: 'How did that feel?',
  acceptedAnswers: 'Accepted answers', answer: 'Answer',
  noSingleAnswer: 'There is no single correct answer. Choose how confidently you answered.',
  confident: 'Confident', good: 'Good', again: 'Again', tryAgain: 'Try again', practiceSaveError: 'Your practice could not be saved. Try again.',
  practiceChanged: 'This exercise has changed. Your answer is still here. Load the current exercise to start again.',
  practiceUnavailable: 'This exercise is no longer assigned to you.', refreshPractice: 'Load current exercise',
  practiceRefreshError: 'The current exercise could not be loaded. Try again.', continuePractice: 'Continue practice',
  audioTooLarge: 'Choose an audio file under 20 MB.', audioTooLong: 'Keep your response under five minutes.',
  audioOpenError: 'This audio could not be opened. Try another recording or an MP3, M4A, or WAV file.',
  recordingTooLarge: 'The recording is too large. Try a shorter response.',
  recordingStopped: 'Recording stopped unexpectedly. Try again or choose an audio file.',
  microphoneUnavailable: 'The microphone is unavailable. Allow microphone access and try again, or choose an audio file.',
  recordingLimit: 'You have ten retained recordings for this task. Trashed audio is cleared after seven days. Keep your download and ask your tutor about the next task.',
  voiceChanged: 'The task has changed. Download your recording before reloading to see the revised task.',
  voiceSendError: 'Your recording could not be sent. Keep this page open and try again.',
  voiceResponse: 'Voice response', responseSent: 'Response sent', stopRecording: 'Stop recording', recordingTime: 'Recording time',
  recordAgain: 'Record again', recordAnother: 'Record another response', recordResponse: 'Record response', chooseFile: 'Choose audio file',
  preparing: 'Preparing your recording…', preview: 'Preview your response', sendResponse: 'Send response', download: 'Download recording', sending: 'Sending recording…',
  voicePrivacy: `Up to five minutes. Audio files up to 20 MB. Only you and your tutors can listen. Recordings are removed after ${VOICE_RETENTION_DAYS} days; you can remove yours sooner.`,
  recordingUnavailable: 'This recording has been removed or has expired.', recordingLoadError: 'Could not load the recording. Try again.',
  recordingRemoveError: 'Could not remove the recording. Try again.', recordingRestoreError: 'Could not restore the recording. It may have expired.',
  loadingRecording: 'Loading recording…', listen: (time: string) => `Listen · ${time}`, listenAt: (time: string) => `Listen at ${time}`,
  removeRecording: 'Remove recording', restoreRecording: 'Restore recording',
  removedFeedbackRemains: 'This recording has been removed or has expired. Feedback stays available.',
  removeQuestion: 'Remove this recording?',
  removeExplanation: 'The recording moves to trash and can be restored for seven days, unless its 90-day retention ends sooner. Feedback stays available.',
  keepRecording: 'Keep recording', trashAudio: 'Move audio to trash',
};

export type LearnerCopy = typeof en;
export type LearnerMessage = { [K in keyof LearnerCopy]: LearnerCopy[K] extends string ? K : never }[keyof LearnerCopy];

const fr: LearnerCopy = {
  interfaceLanguage: 'Langue de l’interface', close: 'Fermer',
  deadLink: 'Ce lien ne fonctionne plus', newLink: 'Demandez un nouveau lien à votre professeur.',
  tooManyAttempts: 'Trop de tentatives',
  rateLimit: 'Trop de tentatives ont été faites depuis cette connexion. Rechargez la page dans une minute. Votre lien reste valable.',
  rateLimitShort: 'Trop de tentatives depuis votre connexion. Attendez une minute, puis rechargez la page.',
  loading: 'Chargement…', learning: 'Apprentissage', lesson: 'Cours', practice: 'Exercices', feedback: 'Retours',
  lessonsError: 'Impossible de charger vos cours pour le moment. Réessayez dans un instant.',
  lessonEmpty: 'Votre cours apparaîtra ici une fois partagé par votre professeur.', earlierSessions: 'Cours précédents',
  loadingPractice: 'Chargement des exercices…', practiceLoadError: 'Impossible de charger les exercices. Rechargez la page dans un instant.',
  practiceDone: 'Vous avez terminé vos exercices pour le moment. Revenez plus tard pour réviser.', revisit: 'Reprendre les exercices',
  loadingFeedback: 'Chargement des retours…', feedbackLoadError: 'Impossible de charger les retours. Rechargez la page dans un instant.',
  feedbackEmpty: 'Les retours de votre professeur apparaîtront ici.', yourWords: 'Votre formulation', tryThis: 'Formulation proposée', yourResponse: 'Votre réponse',
  personalLink: 'Ce lien est personnel. Ne le partagez pas. Si vous le perdez, demandez un nouveau lien à votre professeur.',
  thisSession: 'Ce cours', nothingWritten: 'Aucun compte rendu pour le moment.', outcomes: 'Ce que nous avons appris', materials: 'Documents',
  reading: 'Lecture', writing: 'Expression écrite', quiz: 'Exercice',
  saved: 'Enregistré', saving: 'Enregistrement…', save: 'Enregistrer',
  writingChanged: 'La consigne a changé. Copiez votre texte avant de recharger la page pour consulter la nouvelle consigne.',
  writingError: 'Votre texte n’a pas pu être enregistré. Gardez cette page ouverte et réessayez.',
  yourAnswer: 'Votre réponse', chooseAll: 'Choisissez toutes les réponses qui conviennent.',
  gap: (number) => `Trou ${number}`, match: (label) => `Associer ${label}`, chooseMatch: 'Choisir une correspondance',
  moveUp: (label) => `Monter ${label}`, moveDown: (label) => `Descendre ${label}`,
  check: 'Vérifier', correct: 'C’est juste.', compare: 'Comparez votre réponse.', selfCheck: 'Comment cela s’est-il passé ?',
  acceptedAnswers: 'Réponses acceptées', answer: 'Réponse',
  noSingleAnswer: 'Il n’y a pas de réponse unique. Indiquez si vous êtes à l’aise avec votre réponse.',
  confident: 'À l’aise', good: 'Bien compris', again: 'À revoir', tryAgain: 'Réessayer', practiceSaveError: 'Votre exercice n’a pas pu être enregistré. Réessayez.',
  practiceChanged: 'Cet exercice a changé. Votre réponse est toujours ici. Chargez l’exercice actuel pour recommencer.',
  practiceUnavailable: 'Cet exercice ne vous est plus attribué.', refreshPractice: 'Charger l’exercice actuel',
  practiceRefreshError: 'Impossible de charger l’exercice actuel. Réessayez.', continuePractice: 'Continuer les exercices',
  audioTooLarge: 'Choisissez un fichier audio de moins de 20 Mo.', audioTooLong: 'Votre réponse doit durer moins de cinq minutes.',
  audioOpenError: 'Impossible d’ouvrir cet audio. Essayez un autre enregistrement ou un fichier MP3, M4A ou WAV.',
  recordingTooLarge: 'L’enregistrement est trop volumineux. Essayez une réponse plus courte.',
  recordingStopped: 'L’enregistrement s’est arrêté. Réessayez ou choisissez un fichier audio.',
  microphoneUnavailable: 'Le microphone n’est pas disponible. Autorisez son accès et réessayez, ou choisissez un fichier audio.',
  recordingLimit: 'Vous avez dix enregistrements conservés pour cette consigne. Les audios dans la corbeille sont effacés après sept jours. Gardez votre copie téléchargée et contactez votre professeur pour la suite.',
  voiceChanged: 'La consigne a changé. Téléchargez votre enregistrement avant de recharger la page pour consulter la nouvelle consigne.',
  voiceSendError: 'Votre enregistrement n’a pas pu être envoyé. Gardez cette page ouverte et réessayez.',
  voiceResponse: 'Réponse orale', responseSent: 'Réponse envoyée', stopRecording: 'Arrêter l’enregistrement', recordingTime: 'Durée de l’enregistrement',
  recordAgain: 'Recommencer', recordAnother: 'Enregistrer une autre réponse', recordResponse: 'Enregistrer une réponse', chooseFile: 'Choisir un fichier audio',
  preparing: 'Préparation de votre enregistrement…', preview: 'Écouter votre réponse', sendResponse: 'Envoyer la réponse', download: 'Télécharger l’enregistrement', sending: 'Envoi de l’enregistrement…',
  voicePrivacy: `Cinq minutes maximum. Fichiers audio de 20 Mo maximum. Seuls vous et vos professeurs pouvez les écouter. Les enregistrements sont supprimés après ${VOICE_RETENTION_DAYS} jours. Vous pouvez supprimer les vôtres avant.`,
  recordingUnavailable: 'Cet enregistrement a été supprimé ou a expiré.', recordingLoadError: 'Impossible de charger l’enregistrement. Réessayez.',
  recordingRemoveError: 'Impossible de supprimer l’enregistrement. Réessayez.', recordingRestoreError: 'Impossible de restaurer l’enregistrement. Il a peut-être expiré.',
  loadingRecording: 'Chargement de l’enregistrement…', listen: (time) => `Écouter · ${time}`, listenAt: (time) => `Écouter à ${time}`,
  removeRecording: 'Supprimer l’enregistrement', restoreRecording: 'Restaurer l’enregistrement',
  removedFeedbackRemains: 'Cet enregistrement a été supprimé ou a expiré. Les retours restent disponibles.',
  removeQuestion: 'Supprimer cet enregistrement ?',
  removeExplanation: 'L’enregistrement est placé dans la corbeille. Vous pouvez le restaurer pendant sept jours, sauf si sa durée de conservation de 90 jours prend fin avant. Les retours restent disponibles.',
  keepRecording: 'Garder l’enregistrement', trashAudio: 'Mettre l’audio à la corbeille',
};

const de: LearnerCopy = {
  interfaceLanguage: 'Sprache der Oberfläche', close: 'Schliessen',
  deadLink: 'Dieser Link funktioniert nicht mehr', newLink: 'Bitte deine Lehrperson um einen neuen Link.',
  tooManyAttempts: 'Zu viele Versuche',
  rateLimit: 'Über diese Verbindung gab es zu viele Versuche. Lade die Seite in einer Minute neu. Dein Link bleibt gültig.',
  rateLimitShort: 'Zu viele Versuche über deine Verbindung. Warte eine Minute und lade die Seite neu.',
  loading: 'Wird geladen…', learning: 'Lernen', lesson: 'Lektion', practice: 'Üben', feedback: 'Feedback',
  lessonsError: 'Deine Lektionen konnten gerade nicht geladen werden. Versuche es gleich noch einmal.',
  lessonEmpty: 'Deine Lektion erscheint hier, sobald deine Lehrperson sie teilt.', earlierSessions: 'Frühere Lektionen',
  loadingPractice: 'Übungen werden geladen…', practiceLoadError: 'Die Übungen konnten nicht geladen werden. Lade die Seite gleich noch einmal neu.',
  practiceDone: 'Für den Moment bist du mit den Übungen fertig. Komm später zum Wiederholen zurück.', revisit: 'Übungen wiederholen',
  loadingFeedback: 'Feedback wird geladen…', feedbackLoadError: 'Das Feedback konnte nicht geladen werden. Lade die Seite gleich noch einmal neu.',
  feedbackEmpty: 'Hier erscheint das Feedback deiner Lehrperson.', yourWords: 'Deine Formulierung', tryThis: 'Vorschlag', yourResponse: 'Deine Antwort',
  personalLink: 'Dieser Link ist persönlich. Bitte teile ihn nicht. Wenn du ihn verlierst, bekommst du von deiner Lehrperson einen neuen.',
  thisSession: 'Diese Lektion', nothingWritten: 'Es gibt noch keine Notizen.', outcomes: 'Das haben wir gelernt', materials: 'Materialien',
  reading: 'Lesen', writing: 'Schreiben', quiz: 'Übung',
  saved: 'Gespeichert', saving: 'Wird gespeichert…', save: 'Speichern',
  writingChanged: 'Die Aufgabe wurde geändert. Kopiere deinen Text, bevor du die Seite neu lädst, um die neue Aufgabe zu sehen.',
  writingError: 'Dein Text konnte nicht gespeichert werden. Lass diese Seite offen und versuche es erneut.',
  yourAnswer: 'Deine Antwort', chooseAll: 'Wähle alle passenden Antworten.',
  gap: (number) => `Lücke ${number}`, match: (label) => `Zuordnung für ${label}`, chooseMatch: 'Zuordnung wählen',
  moveUp: (label) => `${label} nach oben`, moveDown: (label) => `${label} nach unten`,
  check: 'Prüfen', correct: 'Richtig.', compare: 'Vergleiche deine Antwort.', selfCheck: 'Wie ist es dir gegangen?',
  acceptedAnswers: 'Akzeptierte Antworten', answer: 'Antwort',
  noSingleAnswer: 'Es gibt keine einzelne richtige Antwort. Gib an, wie sicher du dich mit deiner Antwort fühlst.',
  confident: 'Sicher', good: 'Verstanden', again: 'Noch üben', tryAgain: 'Erneut versuchen', practiceSaveError: 'Deine Übung konnte nicht gespeichert werden. Versuche es erneut.',
  practiceChanged: 'Diese Übung wurde geändert. Deine Antwort bleibt hier stehen. Lade die aktuelle Übung, um neu zu beginnen.',
  practiceUnavailable: 'Diese Übung ist dir nicht mehr zugeteilt.', refreshPractice: 'Aktuelle Übung laden',
  practiceRefreshError: 'Die aktuelle Übung konnte nicht geladen werden. Versuche es erneut.', continuePractice: 'Weiterüben',
  audioTooLarge: 'Wähle eine Audiodatei unter 20 MB.', audioTooLong: 'Deine Antwort darf höchstens fünf Minuten dauern.',
  audioOpenError: 'Diese Audiodatei konnte nicht geöffnet werden. Versuche eine andere Aufnahme oder eine MP3-, M4A- oder WAV-Datei.',
  recordingTooLarge: 'Die Aufnahme ist zu gross. Versuche eine kürzere Antwort.',
  recordingStopped: 'Die Aufnahme wurde unerwartet beendet. Versuche es erneut oder wähle eine Audiodatei.',
  microphoneUnavailable: 'Das Mikrofon ist nicht verfügbar. Erlaube den Mikrofonzugriff und versuche es erneut, oder wähle eine Audiodatei.',
  recordingLimit: 'Für diese Aufgabe sind zehn Aufnahmen gespeichert. Aufnahmen im Papierkorb werden nach sieben Tagen gelöscht. Behalte deine heruntergeladene Kopie und frage deine Lehrperson nach der nächsten Aufgabe.',
  voiceChanged: 'Die Aufgabe wurde geändert. Lade deine Aufnahme herunter, bevor du die Seite neu lädst, um die neue Aufgabe zu sehen.',
  voiceSendError: 'Deine Aufnahme konnte nicht gesendet werden. Lass diese Seite offen und versuche es erneut.',
  voiceResponse: 'Mündliche Antwort', responseSent: 'Antwort gesendet', stopRecording: 'Aufnahme beenden', recordingTime: 'Aufnahmedauer',
  recordAgain: 'Neu aufnehmen', recordAnother: 'Weitere Antwort aufnehmen', recordResponse: 'Antwort aufnehmen', chooseFile: 'Audiodatei wählen',
  preparing: 'Deine Aufnahme wird vorbereitet…', preview: 'Deine Antwort anhören', sendResponse: 'Antwort senden', download: 'Aufnahme herunterladen', sending: 'Aufnahme wird gesendet…',
  voicePrivacy: `Höchstens fünf Minuten. Audiodateien bis 20 MB. Nur du und deine Lehrpersonen können sie anhören. Aufnahmen werden nach ${VOICE_RETENTION_DAYS} Tagen gelöscht. Du kannst deine auch früher entfernen.`,
  recordingUnavailable: 'Diese Aufnahme wurde entfernt oder ist abgelaufen.', recordingLoadError: 'Die Aufnahme konnte nicht geladen werden. Versuche es erneut.',
  recordingRemoveError: 'Die Aufnahme konnte nicht entfernt werden. Versuche es erneut.', recordingRestoreError: 'Die Aufnahme konnte nicht wiederhergestellt werden. Sie ist möglicherweise abgelaufen.',
  loadingRecording: 'Aufnahme wird geladen…', listen: (time) => `Anhören · ${time}`, listenAt: (time) => `Ab ${time} anhören`,
  removeRecording: 'Aufnahme entfernen', restoreRecording: 'Aufnahme wiederherstellen',
  removedFeedbackRemains: 'Diese Aufnahme wurde entfernt oder ist abgelaufen. Das Feedback bleibt verfügbar.',
  removeQuestion: 'Diese Aufnahme entfernen?',
  removeExplanation: 'Die Aufnahme kommt in den Papierkorb und kann sieben Tage lang wiederhergestellt werden, sofern ihre Aufbewahrungsfrist von 90 Tagen nicht früher endet. Das Feedback bleibt verfügbar.',
  keepRecording: 'Aufnahme behalten', trashAudio: 'Audio in den Papierkorb',
};

export const learnerCopy: Record<LearnerLocale, LearnerCopy> = { en, fr, de };

/** Interface preference is independent of the lesson's taught/native language pair. */
export function resolveLearnerLocale(saved: string | null, languages: readonly string[]): LearnerLocale {
  if (saved === 'en' || saved === 'fr' || saved === 'de') return saved;
  for (const language of languages) {
    const base = language.toLowerCase().split('-')[0];
    if (base === 'en' || base === 'fr' || base === 'de') return base;
  }
  return 'en';
}
