import { expect, type Page } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { test } from '../fixtures/learner-browser';

const output = fileURLToPath(new URL('../../apps/site/public/docs/images/', import.meta.url));

async function capture(page: Page, name: string, fullPage = false) {
  await page.evaluate(() => document.fonts.ready);
  await page.mouse.move(0, 0);
  await page.screenshot({ path: `${output}${name}.png`, fullPage, animations: 'disabled' });
}

test('capture the manual from a real local teaching journey', async ({ page, learnerBrowser }) => {
  test.skip(process.env.UPDATE_MANUAL_SCREENSHOTS !== '1', 'Explicit screenshot refresh only.');
  test.setTimeout(180_000);
  await mkdir(output, { recursive: true });
  await page.goto('/host/');
  await page.getByLabel('Username', { exact: true }).fill('cara');
  await page.getByLabel('Password', { exact: true }).fill('demo');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await page.getByRole('link', { name: 'Choose experience', exact: true }).click();
  await page.getByRole('radio', { name: /^Tutoring / }).check();
  await page.getByRole('button', { name: 'Save experience', exact: true }).click();
  await page.getByRole('link', { name: 'Add student or group', exact: true }).click();
  await page.getByLabel('Name', { exact: true }).fill('Camille');
  await page.getByRole('button', { name: 'B1', exact: true }).click();
  await page.getByLabel('Goal', { exact: true }).fill('Explain a travel problem in French.');
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await page.getByText('Student access links', { exact: true }).click();
  await page.getByRole('link', { name: 'Create link', exact: true }).click();
  await page.getByRole('button', { name: 'Create link', exact: true }).click();
  const learnerUrl = await page.locator('code').filter({ hasText: '#/learn?token=' }).innerText();
  await page.getByRole('link', { name: 'Done', exact: true }).click();
  await page.getByRole('link', { name: 'Sample lessons', exact: true }).click();
  await page.getByRole('group', { name: 'Lesson language' }).getByRole('button', { name: 'Français', exact: true }).click();
  await page.getByRole('group', { name: 'Lesson level' }).getByRole('button', { name: 'B1', exact: true }).click();
  await page.getByRole('button', { name: 'Open Le train est parti', exact: true }).click();
  const slides = page.getByRole('list', { name: 'Slides', exact: true }).getByRole('button');
  await expect(slides).toHaveCount(12);
  await expect(page).toHaveURL(/#\/decks\/[^/]+\/edit/);
  const editorUrl = page.url();
  await slides.nth(3).click();
  await capture(page, 'deck-editor');
  await slides.nth(6).click();
  await page.locator('.slide-canvas__frame [data-part="header"]').click();
  await expect(page.getByRole('button', { name: 'Gap selected text', exact: true })).toBeVisible();
  await capture(page, 'gap-exercise');
  await page.getByRole('link', { name: 'Back', exact: true }).click();
  await expect(page.getByRole('listbox', { name: 'Library', exact: true })).toBeVisible();
  await page.getByRole('option').filter({ hasText: 'Le train est parti' }).click();
  await capture(page, 'library');
  await page.goto(editorUrl);
  await page.getByRole('button', { name: 'Start session', exact: true }).click();
  const presenter = page.getByRole('dialog', { name: 'Presenter', exact: true });
  await presenter.getByRole('button', { name: 'Session menu', exact: true }).click();
  const joinUrl = await page.getByRole('menuitem', { name: 'Join page', exact: true }).getAttribute('href');
  expect(joinUrl).toBeTruthy();
  await page.keyboard.press('Escape');
  const phone = await learnerBrowser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true, locale: 'en-GB', reducedMotion: 'reduce' });
  const participant = await phone.newPage();
  await participant.goto(joinUrl!);
  await participant.getByRole('button', { name: 'Join', exact: true }).click();
  const liveSlides = presenter.getByRole('tablist', { name: 'Slides', exact: true }).getByRole('tab');
  await liveSlides.nth(3).click();
  await participant.getByRole('button', { name: 'Reading', exact: true }).click();
  await expect(participant.getByText(/Il pleuvait et le bus avançait lentement/)).toBeVisible();
  const dismiss = participant.getByRole('button', { name: 'Dismiss', exact: true });
  if (await dismiss.isVisible()) await dismiss.click();
  await capture(participant, 'phone-reading', true);
  await liveSlides.nth(4).click();
  await participant.getByRole('radio', { name: 'Arriver avant 18 h.', exact: true }).click();
  await expect(participant.getByText('Answer received', { exact: true })).toBeVisible();
  await presenter.getByRole('button', { name: 'Reveal the results', exact: true }).click();
  await expect(presenter.locator('.stage-mirror .barrow__label')).toHaveCount(3);
  await expect(presenter.locator('.moment__title')).toHaveText('Results');
  await expect(presenter.locator('.moment__title')).toHaveCSS('opacity', '0');
  await capture(page, 'live-results');
  await presenter.getByRole('textbox', { name: 'Private notes', exact: true }).fill('Revisit the difference between imparfait and passé composé.');
  await presenter.locator('header').getByRole('button', { name: 'End session', exact: true }).click();
  await page.getByRole('dialog', { name: 'End this session?', exact: true }).getByRole('button', { name: 'End session', exact: true }).click();
  await page.getByLabel('Outcomes (one per line)', { exact: true }).fill('You explained the delay and found another route.');
  await page.getByLabel('Next step', { exact: true }).fill('Compare two accounts of the same journey.');
  await page.getByRole('heading', { name: 'Session notes — Le train est parti', exact: true }).click();
  await capture(page, 'session-notes');
  await page.getByRole('button', { name: 'Save notes', exact: true }).click();
  const learner = await phone.newPage();
  await learner.goto(learnerUrl);
  const writing = learner.getByRole('textbox', { name: 'Racontez un trajet qui ne s’est pas passé comme prévu (100 à 130 mots).', exact: true });
  await writing.fill('Il pleuvait. Je suis allé à la gare, mais le train était déjà parti.');
  await learner.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(learner.getByRole('button', { name: 'Saved', exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Review learner work', exact: true }).click();
  await page.getByRole('link', { name: /Camille.*Review response/s }).click();
  await page.getByLabel('Feedback', { exact: true }).fill('Votre récit est clair. Attention à l’accord.');
  await page.getByRole('button', { name: 'Add correction', exact: true }).click();
  await page.getByLabel('Their words', { exact: true }).fill('allé');
  await page.getByLabel('Suggested wording', { exact: true }).fill('allée');
  await page.getByLabel('Why', { exact: true }).fill('Avec être, le participe passé s’accorde avec le sujet.');
  await page.getByRole('button', { name: 'Share feedback', exact: true }).click();
  await expect(page.getByRole('status').filter({ hasText: 'Feedback shared with Camille.' })).toBeVisible();
  await learner.reload();
  await learner.getByRole('tab', { name: 'Feedback', exact: true }).click();
  await expect(learner.getByText('Votre récit est clair. Attention à l’accord.', { exact: true })).toBeVisible();
  await capture(learner, 'phone-feedback', true);
  await phone.close();
});
