import type { Theme, ThemeId, ThemeTokens } from './tokens.js';

/**
 * The five built-in themes, each with a light and a dark token table.
 *
 * Contract for every variant (enforced by `test/contrast.test.ts`):
 *   contrast(foreground, background)             >= 4.5:1
 *   contrast(primary-foreground, primary)        >= 4.5:1
 *   contrast(card-foreground, card)              >= 4.5:1
 *   contrast(popover-foreground, popover)        >= 4.5:1
 *   contrast(secondary-foreground, secondary)    >= 4.5:1
 *   contrast(accent-foreground, accent)          >= 4.5:1
 *   contrast(destructive-foreground, destructive)>= 4.5:1
 *   contrast(muted-foreground, background)       >= 4.5:1
 *   contrast(live-foreground, live)              >= 4.5:1
 *   contrast(live-tint-foreground, live-tint)    >= 4.5:1
 *
 * A session can be switched between these live by the host (`session.theme`), so
 * all five must stay legible on the same projector, mid-session.
 *
 * Structure comes from fill: paper, canvas, chrome and desk are never the same
 * colour next to each other. Two meaningful hues — primary = you can act, live
 * = the class is in it. Flat-Everywhere is retired; two shadows are allowed
 * (`shadow-page` on the desk, `shadow-overlay` on a dialog or menu). Gradients,
 * blur and glow stay banned. Every chart colour is a solid saturated hue that
 * survives a washed-out beamer.
 */

const SEGOE =
  '"Segoe UI Variable Text", "Segoe UI", system-ui, -apple-system, "Helvetica Neue", Arial, sans-serif';
const SANS =
  'ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif';
const SERIF = 'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif';
const ROUNDED =
  'ui-rounded, "SF Pro Rounded", "Hiragino Maru Gothic ProN", "Segoe UI", system-ui, sans-serif';
const CONDENSED =
  '"Helvetica Neue", "Arial Narrow", Roboto, system-ui, -apple-system, sans-serif';

const SHADOW_PAGE = '0 1px 2px rgba(0,0,0,0.12), 0 6px 20px rgba(0,0,0,0.10)';
const SHADOW_OVERLAY = '0 8px 32px rgba(0,0,0,0.26)';
const SHADOW_PAGE_DARK = '0 1px 2px rgba(0,0,0,0.28), 0 6px 24px rgba(0,0,0,0.32)';
const SHADOW_OVERLAY_DARK = '0 8px 32px rgba(0,0,0,0.48)';
/* ------------------------------------------------------------------ */
/* default — paper on a desk, action blue, live orange                 */
/* ------------------------------------------------------------------ */

const defaultLight: ThemeTokens = {
  background: '#FAF9F8',
  foreground: '#242424',
  card: '#FFFFFF',
  'card-foreground': '#242424',
  popover: '#FFFFFF',
  'popover-foreground': '#242424',
  primary: '#0F6CBD',
  'primary-foreground': '#FFFFFF',
  secondary: '#F3F2F1',
  'secondary-foreground': '#242424',
  muted: '#F3F2F1',
  'muted-foreground': '#616161',
  accent: '#EBF3FC',
  'accent-foreground': '#115EA3',
  destructive: '#A4262C',
  'destructive-foreground': '#FFFFFF',
  border: '#E1DFDD',
  input: '#D2D0CE',
  ring: '#0F6CBD',
  radius: '0.25rem',
  'chart-1': '#0F6CBD',
  'chart-2': '#107C41',
  'chart-3': '#B88217',
  'chart-4': '#B4009E',
  'chart-5': '#5C2E91',
  'font-sans': SEGOE,
  'font-display': SEGOE,
  desk: '#E8E6E4',
  chrome: '#F3F2F1',
  hairline: '#EDEBE9',
  live: '#CA5010',
  'live-hover': '#9C3D0B',
  'live-foreground': '#FFFFFF',
  'live-tint': '#FDF1E8',
  'live-tint-foreground': '#9C3D0B',
  'radius-sm': '2px',
  'radius-md': '4px',
  'radius-lg': '6px',
  'radius-xl': '8px',
  'shadow-page': SHADOW_PAGE,
  'shadow-overlay': SHADOW_OVERLAY,
};

const defaultDark: ThemeTokens = {
  background: '#201F1E',
  foreground: '#F3F2F1',
  card: '#292827',
  'card-foreground': '#F3F2F1',
  popover: '#292827',
  'popover-foreground': '#F3F2F1',
  primary: '#4F9AE8',
  'primary-foreground': '#06122B',
  secondary: '#323130',
  'secondary-foreground': '#F3F2F1',
  muted: '#323130',
  'muted-foreground': '#C8C6C4',
  accent: '#163A5C',
  'accent-foreground': '#B3D6F5',
  destructive: '#E85A5A',
  'destructive-foreground': '#2A0808',
  border: '#484644',
  input: '#605E5C',
  ring: '#4F9AE8',
  radius: '0.25rem',
  'chart-1': '#4F9AE8',
  'chart-2': '#54B471',
  'chart-3': '#E8B44A',
  'chart-4': '#E05BC4',
  'chart-5': '#A47BEA',
  'font-sans': SEGOE,
  'font-display': SEGOE,
  desk: '#151413',
  chrome: '#252423',
  hairline: '#3B3A39',
  live: '#CA5010',
  'live-hover': '#9C3D0B',
  'live-foreground': '#FFFFFF',
  'live-tint': '#3D2213',
  'live-tint-foreground': '#F4C7A5',
  'radius-sm': '2px',
  'radius-md': '4px',
  'radius-lg': '6px',
  'radius-xl': '8px',
  'shadow-page': SHADOW_PAGE_DARK,
  'shadow-overlay': SHADOW_OVERLAY_DARK,
};

/* ------------------------------------------------------------------ */
/* chalkboard — deep green-black board, chalk-white text, dusty pastels */
/* ------------------------------------------------------------------ */

const chalkboardLight: ThemeTokens = {
  // The "light" board: a washed sage classroom wall with dark green ink.
  background: '#e9efe6',
  foreground: '#0f2418',
  card: '#f6f9f3',
  'card-foreground': '#0f2418',
  popover: '#f6f9f3',
  'popover-foreground': '#0f2418',
  primary: '#17593a',
  'primary-foreground': '#f2f8ef',
  secondary: '#d5e0d0',
  'secondary-foreground': '#13291c',
  muted: '#dde6d8',
  'muted-foreground': '#445a45',
  accent: '#cfe3d3',
  'accent-foreground': '#123a26',
  destructive: '#a32d16',
  'destructive-foreground': '#fdf5f2',
  border: '#8ea88a',
  input: '#5f7a5c',
  ring: '#17593a',
  radius: '0.125rem',
  'chart-1': '#1f6b45',
  'chart-2': '#6a3fa0',
  'chart-3': '#a85319',
  'chart-4': '#1d5f86',
  'chart-5': '#7a6413',
  'font-sans': SANS,
  'font-display': SERIF,
  desk: '#C8D4C4',
  chrome: '#D5E0D0',
  hairline: '#DDE6D8',
  live: '#A8481C',
  'live-hover': '#8A3A12',
  'live-foreground': '#FFFFFF',
  'live-tint': '#F4E6D8',
  'live-tint-foreground': '#8A3A12',
  'radius-sm': '2px',
  'radius-md': '4px',
  'radius-lg': '6px',
  'radius-xl': '8px',
  'shadow-page': SHADOW_PAGE,
  'shadow-overlay': SHADOW_OVERLAY,
};

const chalkboardDark: ThemeTokens = {
  // The real board: deep green-black slate, chalk white, dusty pastel chalks.
  background: '#0c1a13',
  foreground: '#eef5e8',
  card: '#12241a',
  'card-foreground': '#eef5e8',
  popover: '#12241a',
  'popover-foreground': '#eef5e8',
  primary: '#d9ecd2',
  'primary-foreground': '#0d2016',
  secondary: '#1a3024',
  'secondary-foreground': '#eef5e8',
  muted: '#1a3024',
  'muted-foreground': '#a6c0aa',
  accent: '#1f4230',
  'accent-foreground': '#dff0e0',
  destructive: '#f0a08a',
  'destructive-foreground': '#2a0f08',
  border: '#3a5c46',
  input: '#557a62',
  ring: '#a8d3b4',
  radius: '0.125rem',
  'chart-1': '#8fd6a8',
  'chart-2': '#f0a6c8',
  'chart-3': '#ffdf8a',
  'chart-4': '#9ec8f5',
  'chart-5': '#d0b0f0',
  'font-sans': SANS,
  'font-display': SERIF,
  desk: '#08140E',
  chrome: '#1A3024',
  hairline: '#243C2E',
  live: '#E89A5C',
  'live-hover': '#F2B283',
  'live-foreground': '#1A0C04',
  'live-tint': '#2A1A10',
  'live-tint-foreground': '#F0C49A',
  'radius-sm': '2px',
  'radius-md': '4px',
  'radius-lg': '6px',
  'radius-xl': '8px',
  'shadow-page': SHADOW_PAGE_DARK,
  'shadow-overlay': SHADOW_OVERLAY_DARK,
};

/* ------------------------------------------------------------------ */
/* paper — warm off-white, ink, muted primaries                        */
/* ------------------------------------------------------------------ */

const paperLight: ThemeTokens = {
  background: '#f7f1e6',
  foreground: '#1e1913',
  card: '#fffbf2',
  'card-foreground': '#1e1913',
  popover: '#fffbf2',
  'popover-foreground': '#1e1913',
  primary: '#6b3f18',
  'primary-foreground': '#fdf8ef',
  secondary: '#ece0cd',
  'secondary-foreground': '#2a2118',
  muted: '#eee3d2',
  'muted-foreground': '#5c4f3d',
  accent: '#e4d3ba',
  'accent-foreground': '#3a2c1a',
  destructive: '#9c2f18',
  'destructive-foreground': '#fdf5f2',
  border: '#b09c7d',
  input: '#8a7355',
  ring: '#6b3f18',
  radius: '0.125rem',
  'chart-1': '#8a5a1e',
  'chart-2': '#2f6b52',
  'chart-3': '#9a3b2a',
  'chart-4': '#4b4a86',
  'chart-5': '#7a2f5e',
  'font-sans': SANS,
  'font-display': SERIF,
  desk: '#E4D6BE',
  chrome: '#ECE0CD',
  hairline: '#F0E6D4',
  live: '#C05621',
  'live-hover': '#8B3A12',
  'live-foreground': '#FFFFFF',
  'live-tint': '#F6E6D4',
  'live-tint-foreground': '#8B3A12',
  'radius-sm': '2px',
  'radius-md': '4px',
  'radius-lg': '6px',
  'radius-xl': '8px',
  'shadow-page': SHADOW_PAGE,
  'shadow-overlay': SHADOW_OVERLAY,
};

const paperDark: ThemeTokens = {
  background: '#191411',
  foreground: '#f4ece0',
  card: '#221c17',
  'card-foreground': '#f4ece0',
  popover: '#221c17',
  'popover-foreground': '#f4ece0',
  primary: '#e0c193',
  'primary-foreground': '#201607',
  secondary: '#2c2520',
  'secondary-foreground': '#f4ece0',
  muted: '#2c2520',
  'muted-foreground': '#b7a894',
  accent: '#3a2f24',
  'accent-foreground': '#f4ece0',
  destructive: '#ef9578',
  'destructive-foreground': '#2a0f08',
  border: '#5e4f3f',
  input: '#75634e',
  ring: '#e0c193',
  radius: '0.125rem',
  'chart-1': '#e8c188',
  'chart-2': '#7fc9a5',
  'chart-3': '#f0a05a',
  'chart-4': '#b3a6e0',
  'chart-5': '#ec8f8f',
  'font-sans': SANS,
  'font-display': SERIF,
  desk: '#120E0B',
  chrome: '#2C2520',
  hairline: '#352C24',
  live: '#E8A066',
  'live-hover': '#F2B884',
  'live-foreground': '#201607',
  'live-tint': '#3A2418',
  'live-tint-foreground': '#F4C7A5',
  'radius-sm': '2px',
  'radius-md': '4px',
  'radius-lg': '6px',
  'radius-xl': '8px',
  'shadow-page': SHADOW_PAGE_DARK,
  'shadow-overlay': SHADOW_OVERLAY_DARK,
};

/* ------------------------------------------------------------------ */
/* projector — maximum contrast, radius 0, hues that survive washout   */
/* ------------------------------------------------------------------ */

const projectorLight: ThemeTokens = {
  background: '#ffffff',
  foreground: '#000000',
  card: '#ffffff',
  'card-foreground': '#000000',
  popover: '#ffffff',
  'popover-foreground': '#000000',
  primary: '#0026a8',
  'primary-foreground': '#ffffff',
  secondary: '#e8e8e8',
  'secondary-foreground': '#000000',
  muted: '#eeeeee',
  'muted-foreground': '#3d3d3d',
  accent: '#ffe600',
  'accent-foreground': '#000000',
  destructive: '#b00000',
  'destructive-foreground': '#ffffff',
  border: '#000000',
  input: '#000000',
  ring: '#0026a8',
  radius: '0rem',
  'chart-1': '#0026a8',
  'chart-2': '#007a2f',
  'chart-3': '#b00000',
  'chart-4': '#6a00a8',
  'chart-5': '#8a5000',
  'font-sans': CONDENSED,
  'font-display': CONDENSED,
  desk: '#D0D0D0',
  chrome: '#E8E8E8',
  hairline: '#EEEEEE',
  live: '#C44000',
  'live-hover': '#932F00',
  'live-foreground': '#FFFFFF',
  'live-tint': '#FFE0C0',
  'live-tint-foreground': '#000000',
  'radius-sm': '0rem',
  'radius-md': '0rem',
  'radius-lg': '0rem',
  'radius-xl': '0rem',
  'shadow-page': 'none',
  'shadow-overlay': 'none',
};

const projectorDark: ThemeTokens = {
  background: '#000000',
  foreground: '#ffffff',
  card: '#000000',
  'card-foreground': '#ffffff',
  popover: '#000000',
  'popover-foreground': '#ffffff',
  primary: '#ffe600',
  'primary-foreground': '#000000',
  secondary: '#1a1a1a',
  'secondary-foreground': '#ffffff',
  muted: '#141414',
  'muted-foreground': '#c4c4c4',
  accent: '#00e5ff',
  'accent-foreground': '#000000',
  destructive: '#ff5252',
  'destructive-foreground': '#000000',
  border: '#ffffff',
  input: '#ffffff',
  ring: '#ffe600',
  radius: '0rem',
  'chart-1': '#ffe600',
  'chart-2': '#00e5ff',
  'chart-3': '#ff5252',
  'chart-4': '#7cff5a',
  'chart-5': '#ff8ae2',
  'font-sans': CONDENSED,
  'font-display': CONDENSED,
  desk: '#0A0A0A',
  chrome: '#1A1A1A',
  hairline: '#2A2A2A',
  live: '#FF6D00',
  'live-hover': '#FF8A2B',
  'live-foreground': '#000000',
  'live-tint': '#331800',
  'live-tint-foreground': '#FFCC80',
  'radius-sm': '0rem',
  'radius-md': '0rem',
  'radius-lg': '0rem',
  'radius-xl': '0rem',
  'shadow-page': 'none',
  'shadow-overlay': 'none',
};

/* ------------------------------------------------------------------ */
/* sherbet — playful oranges, pinks and citrus                         */
/* ------------------------------------------------------------------ */

const sherbetLight: ThemeTokens = {
  background: '#fff4ec',
  foreground: '#3a1810',
  card: '#fffaf5',
  'card-foreground': '#3a1810',
  popover: '#fffaf5',
  'popover-foreground': '#3a1810',
  primary: '#c53a0e',
  'primary-foreground': '#fff6ef',
  secondary: '#ffdfcb',
  'secondary-foreground': '#5c2410',
  muted: '#ffe7d8',
  'muted-foreground': '#7a3c26',
  accent: '#ffd4e4',
  'accent-foreground': '#6e1039',
  destructive: '#b81d3f',
  'destructive-foreground': '#fff6ef',
  border: '#e8875a',
  input: '#c4643a',
  ring: '#c53a0e',
  radius: '1rem',
  'chart-1': '#e04a12',
  'chart-2': '#d1156a',
  'chart-3': '#a87c00',
  'chart-4': '#0a8a6e',
  'chart-5': '#6d3fd1',
  'font-sans': ROUNDED,
  'font-display': ROUNDED,
  desk: '#F0D8C4',
  chrome: '#FFDFCB',
  hairline: '#FFE9DA',
  live: '#A33D00',
  'live-hover': '#7D2F00',
  'live-foreground': '#FFFFFF',
  'live-tint': '#FFF0D6',
  'live-tint-foreground': '#9A4A00',
  'radius-sm': '6px',
  'radius-md': '10px',
  'radius-lg': '14px',
  'radius-xl': '1rem',
  'shadow-page': SHADOW_PAGE,
  'shadow-overlay': SHADOW_OVERLAY,
};

const sherbetDark: ThemeTokens = {
  background: '#26121a',
  foreground: '#ffe9dc',
  card: '#321a22',
  'card-foreground': '#ffe9dc',
  popover: '#321a22',
  'popover-foreground': '#ffe9dc',
  primary: '#ff9d5c',
  'primary-foreground': '#2b1005',
  secondary: '#3f212a',
  'secondary-foreground': '#ffe9dc',
  muted: '#3f212a',
  'muted-foreground': '#d8ab9f',
  accent: '#4e2436',
  'accent-foreground': '#ffd8e8',
  destructive: '#ff7d97',
  'destructive-foreground': '#2b0611',
  border: '#7d4150',
  input: '#96525f',
  ring: '#ff9d5c',
  radius: '1rem',
  'chart-1': '#ff9d5c',
  'chart-2': '#ff7fae',
  'chart-3': '#ffd45e',
  'chart-4': '#4fd9b6',
  'chart-5': '#bda2ff',
  'font-sans': ROUNDED,
  'font-display': ROUNDED,
  desk: '#1A0C12',
  chrome: '#3F212A',
  hairline: '#4A2834',
  live: '#FFB020',
  'live-hover': '#FFC44F',
  'live-foreground': '#2B1005',
  'live-tint': '#4A2A12',
  'live-tint-foreground': '#FFD08A',
  'radius-sm': '6px',
  'radius-md': '10px',
  'radius-lg': '14px',
  'radius-xl': '1rem',
  'shadow-page': SHADOW_PAGE_DARK,
  'shadow-overlay': SHADOW_OVERLAY_DARK,
};

/** Built-in themes carry no branding overrides; Pro customisation fills these. */
const NO_BRANDING = { accent: null, logo: null } as const;

export const THEMES: Record<ThemeId, Theme> = {
  default: {
    id: 'default',
    name: 'Default',
    description: 'White, blue accent, orange live markers.',
    branding: { ...NO_BRANDING },
    light: defaultLight,
    dark: defaultDark,
  },
  chalkboard: {
    id: 'chalkboard',
    name: 'Chalkboard',
    description: 'Green-black, white text, pastel accents.',
    branding: { ...NO_BRANDING },
    light: chalkboardLight,
    dark: chalkboardDark,
  },
  paper: {
    id: 'paper',
    name: 'Paper',
    description: 'Off-white, dark text, muted primaries.',
    branding: { ...NO_BRANDING },
    light: paperLight,
    dark: paperDark,
  },
  projector: {
    id: 'projector',
    name: 'Projector',
    description: 'Maximum contrast, square corners.',
    branding: { ...NO_BRANDING },
    light: projectorLight,
    dark: projectorDark,
  },
  sherbet: {
    id: 'sherbet',
    name: 'Sherbet',
    description: 'Orange, pink, citrus; rounded corners.',
    branding: { ...NO_BRANDING },
    light: sherbetLight,
    dark: sherbetDark,
  },
};

/** Theme list in picker order. */
export const THEME_LIST: readonly Theme[] = [
  THEMES.default,
  THEMES.chalkboard,
  THEMES.paper,
  THEMES.projector,
  THEMES.sherbet,
];
