import { test, expect, type Page } from '@playwright/test';
import { parse as parseYaml } from 'yaml';
import { encodeVoiceWav } from '../../packages/schema/src/voice-audio';
import { joinInBrowser, stageUrl, waitForWorker } from '../fixtures/session';

const CSRF = { 'x-openroom-csrf': '1' };
const transcript = 'Der Termin fällt aus. Wir treffen uns am Donnerstag um halb zehn.';
const tone = Buffer.from(encodeVoiceWav(Float32Array.from({ length: 16_000 * 20 }, (_, i) => Math.sin(i * 2 * Math.PI * 440 / 16_000) * 0.02)));
const playing = (page: Page) => page.locator('audio').evaluateAll((items) => items.filter((item) => !(item as HTMLAudioElement).paused).length);

test.beforeAll(async () => { await waitForWorker(); });
test('author a recording, choose the playback audience, reveal the transcript and leave the slide silently', async ({ page, browser }, testInfo) => {
  await page.request.post('/api/auth/demo/login', { headers: CSRF, data: { username: 'bob', password: 'demo' } });
  const cookies = await page.context().cookies();
  await page.context().clearCookies();
  await page.context().addCookies(cookies.map((cookie) => ({ ...cookie, secure: false })));
  const { context } = await (await page.request.post('/api/tutoring/contexts', { headers: CSRF, data: { displayName: 'Camille', kind: 'person', experience: 'tutoring' } })).json();
  const { deck } = await (await page.request.post('/api/decks', { headers: CSRF, data: { spaceId: context.spaceId, contextId: context.id, content: {
    version: 1, meta: { title: 'Un changement de rendez-vous' }, defaults: { identityMode: 'pseudonymous' }, interactions: [], steps: [
      { id: 'listen', kind: 'media', title: 'Listen for the new time', media: { type: 'audio', url: 'https://local.openroom.invalid/openroom-pending-audio', alt: 'The appointment', listening: { mode: 'room' } } },
      { id: 'next', kind: 'title', title: 'When is the appointment?' },
    ],
  } } })).json();
  await page.goto(`/host/#/decks/${deck.id}/edit`);
  await page.getByLabel('Audio file', { exact: true }).setInputFiles({ name: 'appointment.wav', mimeType: 'audio/wav', buffer: tone });
  await expect(page.getByLabel('Audio address', { exact: true })).toHaveValue(/\/api\/assets\//);
  await page.getByLabel('Recording label', { exact: true }).fill('A changed appointment');
  await page.getByLabel('Transcript', { exact: true }).fill(transcript);
  await page.getByLabel('Transcript', { exact: true }).press('Tab');
  await expect(page.locator('[data-or-draft-status]')).toHaveAttribute('data-or-draft-status', 'saved');
  const saved = parseYaml((await (await page.request.get(`/api/decks/${deck.id}/draft`)).json()).source);
  expect(saved.steps[0].media.listening).toEqual({ mode: 'room', transcript });
  await page.getByRole('button', { name: 'Replay', exact: true }).click();
  await expect.poll(() => playing(page)).toBe(1);
  await page.getByRole('button', { name: 'Present', exact: true }).click();
  const presenter = page.getByRole('dialog', { name: 'Presenter', exact: true });
  const controls = presenter.getByRole('region', { name: 'Listening controls', exact: true });
  await expect.poll(() => playing(page)).toBe(0);
  await controls.getByRole('button', { name: 'Individual listening', exact: true }).click();
  await controls.getByRole('button', { name: 'Show transcript', exact: true }).click();
  const launch = page.waitForResponse((response) => /\/sessions\/[^/]+\/launch$/.test(response.url()) && response.request().method() === 'POST');
  await presenter.getByRole('button', { name: 'Start session', exact: true }).click();
  const launchResponse = await launch;
  expect(launchResponse.status(), await launchResponse.text()).toBe(201);
  const session = await launchResponse.json();
  await expect(controls).toBeVisible();
  const stage = await browser.newPage();
  await stage.goto(stageUrl(session));
  const phone = await browser.newPage({ viewport: { width: 390, height: 844 } });
  await joinInBrowser(phone, session.code);
  await expect(controls.getByRole('button', { name: 'Individual listening', exact: true })).toHaveAttribute('aria-pressed', 'true');
  for (const surface of [stage, phone]) await expect(surface.getByText(transcript, { exact: true })).toBeVisible();
  await expect(phone.locator('audio')).toHaveJSProperty('paused', true);
  await controls.getByRole('button', { name: 'Room audio', exact: true }).click();
  await controls.getByRole('button', { name: 'Hide transcript', exact: true }).click();
  await expect(phone.getByText('Listen together. Your tutor plays the recording.', { exact: true })).toBeVisible();
  if (await phone.getByRole('button', { name: 'Dismiss', exact: true }).isVisible()) await phone.getByRole('button', { name: 'Dismiss', exact: true }).click();
  await expect(stage.locator('audio')).toHaveCount(0);
  await expect(phone.locator('audio')).toHaveCount(0);
  const stageState = await (await page.request.get(`/api/sessions/${session.code}/state?role=stage`, { headers: { authorization: `Bearer ${session.stageToken}` } })).text();
  expect(stageState).not.toContain(transcript);
  await expect(controls.locator('audio')).toHaveJSProperty('paused', true);
  await expect.poll(() => playing(page)).toBe(0);
  await controls.getByRole('button', { name: 'Replay', exact: true }).click();
  await expect(controls.locator('audio')).toHaveJSProperty('paused', false);
  await controls.getByRole('button', { name: '0.75×', exact: true }).click();
  await expect(controls.locator('audio')).toHaveJSProperty('playbackRate', 0.75);
  await controls.getByRole('button', { name: 'Show transcript', exact: true }).click();
  for (const surface of [stage, phone]) await expect(surface.getByText(transcript, { exact: true })).toBeVisible();
  await controls.getByRole('button', { name: 'Hide transcript', exact: true }).click();
  for (const surface of [stage, phone]) await expect(surface.getByText(transcript, { exact: true })).toHaveCount(0);
  await phone.route('**/api/assets/**', (route) => route.fulfill({ status: 503, body: 'Temporary failure' }));
  await controls.getByRole('button', { name: 'Individual listening', exact: true }).click();
  await expect(controls.locator('audio')).toHaveCount(0);
  await expect.poll(() => playing(page)).toBe(0);
  await expect(phone.locator('audio')).toHaveCount(1);
  await expect(phone.locator('audio')).toHaveJSProperty('paused', true);
  await expect(phone.getByRole('alert')).toContainText('This audio could not be loaded');
  await phone.unroute('**/api/assets/**');
  await phone.getByRole('button', { name: 'Retry loading', exact: true }).click();
  await phone.getByRole('button', { name: 'Replay', exact: true }).click();
  await expect(phone.locator('audio')).toHaveJSProperty('paused', false);
  await phone.getByRole('button', { name: '1.25×', exact: true }).click();
  await expect(phone.locator('audio')).toHaveJSProperty('playbackRate', 1.25);
  await phone.screenshot({ path: testInfo.outputPath('individual-listening-phone.png'), fullPage: true });
  await page.screenshot({ path: testInfo.outputPath('listening-host.png') });
  await controls.getByRole('button', { name: 'Room audio', exact: true }).click();
  await expect(phone.locator('audio')).toHaveCount(0);
  await expect(controls.locator('audio')).toHaveJSProperty('paused', true);
  await controls.getByRole('button', { name: 'Show transcript', exact: true }).click();
  await controls.getByRole('button', { name: 'Replay', exact: true }).click();
  await presenter.getByRole('button', { name: /When is the appointment\?/ }).click();
  await expect(stage.getByText('When is the appointment?', { exact: true })).toBeVisible();
  await expect(controls).toHaveCount(0);
  await expect.poll(() => playing(page)).toBe(0);
  await presenter.getByRole('button', { name: /Listen for the new time/ }).click();
  await expect(controls.getByRole('button', { name: 'Room audio', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(controls.locator('audio')).toHaveJSProperty('paused', true);
  for (const surface of [stage, phone]) await expect(surface.getByText(transcript, { exact: true })).toHaveCount(0);
  const remote = await browser.newPage({ viewport: { width: 390, height: 844 } });
  await remote.goto(`${new URL(page.url()).origin}/host/#/sessions/${session.sessionCode}/remote?token=${encodeURIComponent(session.hostToken)}`);
  const remoteControls = remote.getByRole('region', { name: 'Listening controls', exact: true });
  await expect(remoteControls.locator('audio')).toHaveJSProperty('paused', true);
  await remoteControls.getByRole('button', { name: 'Show transcript', exact: true }).click();
  for (const surface of [stage, phone]) await expect(surface.getByText(transcript, { exact: true })).toBeVisible();
  await expect(controls.getByRole('button', { name: 'Hide transcript', exact: true })).toBeVisible();
  await remote.screenshot({ path: testInfo.outputPath('listening-remote.png'), fullPage: true });
  await remoteControls.getByRole('button', { name: 'Hide transcript', exact: true }).click();
  for (const surface of [stage, phone]) await expect(surface.getByText(transcript, { exact: true })).toHaveCount(0);
  await remote.close(); await stage.close(); await phone.close();
});
