import { test, expect } from '@playwright/test';
import { parse as parseYaml } from 'yaml';
import { waitForWorker } from '../fixtures/session';

const CSRF = { 'x-openroom-csrf': '1' };
test.beforeAll(async () => { await waitForWorker(); });

test('tutor chooses original exercises for the next lesson without copying private learner work', async ({ page, browser }, testInfo) => {
  await page.request.post('/api/auth/demo/login', { headers: CSRF, data: { username: 'alice', password: 'demo' } });
  const cookies = await page.context().cookies();
  await page.context().clearCookies();
  await page.context().addCookies(cookies.map((cookie) => ({ ...cookie, secure: false })));
  const { context } = await (await page.request.post('/api/tutoring/contexts', { headers: CSRF, data: { displayName: 'Conversation group', kind: 'group', experience: 'tutoring' } })).json();
  const createDeck = async (title: string, createSession = false) => (await (await page.request.post('/api/decks', { headers: CSRF, data: { contextId: context.id, spaceId: context.spaceId, createSession,
    content: { version: 1, meta: { title }, steps: [{ id: 'title', kind: 'title', title }], interactions: [] },
  } })).json());
  const previous = await createDeck('Previous lesson', true);
  const sessionId = previous.session.id;
  expect((await page.request.post(`/api/sessions/${sessionId}/launch`, { headers: CSRF, data: { start: true } })).status()).toBe(201);
  const choice = { id: 'choice', kind: 'quiz', title: 'Le passé composé', interaction: { id: 'choice', type: 'choice', prompt: 'Quelle phrase est correcte ?', options: [{ id: 'a', label: 'Je va à Paris.' }, { id: 'b', label: 'Je suis allé à Paris.', correct: true }] } };
  const gap = { id: 'gap', kind: 'quiz', title: 'Das Verb', interaction: { id: 'gap', type: 'fill-the-gaps', prompt: 'Ich {{verb}} aus {{country}}.', gaps: [{ id: 'verb', answers: ['komme'] }, { id: 'country', answers: ['Deutschland', 'Österreich'] }], match: { locale: 'de', accents: 'require' } } };
  const opinion = { id: 'opinion', kind: 'quiz', title: 'Travel plans', interaction: { id: 'opinion', type: 'text', prompt: 'Où aimeriez-vous aller ?' } };
  expect((await page.request.put(`/api/sessions/${sessionId}/record`, { headers: CSRF, data: { homework: [choice, gap, opinion] } })).status()).toBe(200);
  const mint = async (displayName: string) => (await (await page.request.post(`/api/tutoring/contexts/${context.id}/links`, { headers: CSRF, data: { displayName } })).json());
  const lea = await mint('Léa'); const noor = await mint('Noor');
  const answer = async (token: string, taskId: string, answer: unknown) => {
    expect((await page.request.post('/api/learner/practice', { headers: { authorization: `Bearer ${token}` }, data: { itemId: `${sessionId}:${taskId}`, assignmentRevision: 1, attemptId: crypto.randomUUID(), grade: 'again', answer } })).status()).toBe(200);
  };
  await answer(lea.token, 'choice', { kind: 'choice', optionIds: ['a'] });
  await answer(lea.token, 'gap', { kind: 'fill-the-gaps', gaps: { verb: 'kommt', country: 'Deutschland' } });
  await answer(noor.token, 'opinion', { kind: 'text', text: 'PRIVATE RESPONSE: my family plans.' });
  // Reuse must come from the original answered exercise, even after a tutor edit.
  expect((await page.request.put(`/api/sessions/${sessionId}/record`, { headers: CSRF, data: { homeworkRevision: 1, homework: [{ ...choice, interaction: { ...choice.interaction, prompt: 'NEW QUESTION AFTER ANSWER' } }, gap, opinion] } })).status()).toBe(200);
  const next = await createDeck('Next lesson');
  await page.route(`**/api/tutoring/contexts/${context.id}/returned`, (route) => route.fulfill({ status: 503, contentType: 'application/json', body: '{}' }), { times: 2 });
  await page.goto(`/host/#/decks/${next.deck.id}/edit`);
  await page.getByRole('button', { name: 'Notes', exact: true }).click();
  await expect(page.getByRole('alert').filter({ hasText: 'Learner work could not be loaded.' })).toBeVisible();
  await page.getByRole('button', { name: 'Retry learner work', exact: true }).click();
  const picker = page.locator('section').filter({ has: page.getByRole('heading', { name: 'Practice to revisit', exact: true }) });
  const choiceItem = picker.locator('details').filter({ has: page.getByText('Léa · Le passé composé', { exact: true }) });
  await choiceItem.locator('summary').click();
  await expect(choiceItem.getByText('Quelle phrase est correcte ?', { exact: true })).toBeVisible();
  await expect(choiceItem.getByText('Je suis allé à Paris.', { exact: true })).toBeVisible();
  await choiceItem.getByRole('button', { name: 'Add as a slide', exact: true }).click();
  await expect(page.getByRole('list', { name: 'Slides' }).getByRole('button')).toHaveCount(2);
  await expect(page.locator('.slide-canvas__frame [data-part="header"]')).toContainText(choice.interaction.prompt);
  await expect(choiceItem.getByRole('status')).toHaveText('Exercise added as a slide.');
  await choiceItem.getByRole('button', { name: 'Add to homework', exact: true }).click();
  await expect(choiceItem.getByRole('status')).toHaveText('Exercise added to homework.');
  const gapItem = picker.locator('details').filter({ has: page.getByText('Léa · Das Verb', { exact: true }) });
  await gapItem.locator('summary').click();
  await gapItem.getByRole('button', { name: 'Add to homework', exact: true }).click();
  await expect(gapItem.getByRole('status')).toHaveText('Exercise added to homework.');
  await expect(page.locator('[data-or-draft-status]')).toHaveAttribute('data-or-draft-status', 'saved');
  const draft = await (await page.request.get(`/api/decks/${next.deck.id}/draft`)).json();
  const outline = parseYaml(draft.source);
  expect(outline.steps).toHaveLength(2);
  expect(outline.homework.tasks).toHaveLength(2);
  expect(outline.interactions.map((item: { type: string }) => item.type)).toEqual(['choice', 'choice', 'fill-the-gaps']);
  expect(outline.interactions[0].options).toEqual(choice.interaction.options);
  expect(outline.interactions[2].gaps).toEqual(gap.interaction.gaps);
  for (const privateValue of ['Léa', 'Noor', 'PRIVATE RESPONSE', 'NEW QUESTION AFTER ANSWER', lea.learnerId, noor.learnerId, sessionId]) expect(draft.source).not.toContain(privateValue);
  await page.screenshot({ path: testInfo.outputPath('selected-practice-next-lesson.png') });
  const launched = page.waitForResponse((response) => /\/api\/sessions\/[^/]+\/launch$/.test(response.url()) && response.request().method() === 'POST');
  await page.getByRole('button', { name: 'Start session', exact: true }).click();
  const launch = await launched;
  expect(launch.status()).toBe(201);
  const nextSessionId = /\/sessions\/([^/]+)\/launch$/.exec(launch.url())![1]!;
  const presenter = page.getByRole('dialog', { name: 'Presenter', exact: true });
  await expect(presenter.getByRole('button', { name: 'End session', exact: true })).toBeVisible();
  await presenter.locator('.stage-mirror').click();
  await page.keyboard.press('ArrowRight');
  await expect(presenter.locator('.stage-mirror')).toContainText(choice.interaction.prompt);
  await presenter.getByRole('textbox', { name: 'Private notes', exact: true }).fill('PRIVATE LIVE NOTE: revisit the verb agreement.');
  await presenter.locator('header').getByRole('button', { name: 'End session', exact: true }).click();
  await page.getByRole('dialog', { name: 'End this session?', exact: true }).getByRole('button', { name: 'End session', exact: true }).click();
  await expect(page).toHaveURL(new RegExp(`/sessions/${nextSessionId}/record`));
  await expect(page.getByLabel('Tutor notes', { exact: true })).toHaveValue('PRIVATE LIVE NOTE: revisit the verb agreement.');
  await page.getByRole('button', { name: 'Save notes', exact: true }).click();
  await expect(page).toHaveURL(new RegExp(`/space/${context.spaceId}`));
  const learner = await browser.newPage({ viewport: { width: 390, height: 844 } });
  await learner.goto(`/host/#/learn?token=${lea.token}`);
  await expect(learner.getByRole('heading', { name: 'Léa', exact: true })).toBeVisible();
  await learner.getByRole('tab', { name: 'Practice', exact: true }).click();
  const available = await (await page.request.get('/api/learner/practice', { headers: { authorization: `Bearer ${lea.token}` } })).json();
  const newItems = available.items.filter((item: { itemId: string }) => item.itemId.startsWith(`${nextSessionId}:`));
  expect(newItems.map((item: { interaction: { type: string } }) => item.interaction.type)).toEqual(['choice', 'fill-the-gaps']);
  expect(newItems[0].interaction.options).toEqual(choice.interaction.options);
  expect(newItems[1].interaction.gaps).toEqual(gap.interaction.gaps);
  const learnerSessions = await page.request.get('/api/learner/sessions', { headers: { authorization: `Bearer ${lea.token}` } });
  expect(await learnerSessions.text()).not.toContain('PRIVATE LIVE NOTE');
  await learner.close();
});
