import { build } from 'esbuild';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const output = await build({
  entryPoints: [resolve(packageRoot, 'ui/main.tsx')],
  bundle: true,
  write: false,
  format: 'iife',
  platform: 'browser',
  target: ['es2022'],
  minify: true,
  define: { 'process.env.NODE_ENV': '"production"' },
  jsx: 'automatic',
  loader: { '.css': 'text' },
});
const script = output.outputFiles?.[0]?.text;
if (script === undefined) throw new Error('preview bundle was not produced');
const target = resolve(packageRoot, 'src/generated/deck-preview-script.ts');
await mkdir(dirname(target), { recursive: true });
await writeFile(target, `// Generated by scripts/build-preview.mjs.\nexport const DECK_PREVIEW_SCRIPT = ${JSON.stringify(script)};\n`);
