export {
  INSERT_CATALOG,
  INSERT_KINDS,
  INSERT_TOP,
  insertIdBase,
  starterStep,
  LIST_TARGETS,
  type InsertGroup,
  type InsertItem,
  type InsertKind,
  type InsertStarter,
  type ListTarget,
} from './catalog';
export {
  type Block,
  STEP_KIND_WORDS,
  askTheClassCount,
  asksTheClass,
  clearPairWork,
  duplicateStep,
  hasMinutes,
  insertAfter,
  moveBlock,
  orderedBlocks,
  removeStep,
  setDurationSeconds,
  setLayout,
  setMinutes,
  setReveal,
  setTimerPersist,
  setTimerPlacement,
  setTimerStyle,
  splitForPairWork,
  stepMinutes,
  stepSeconds,
  stepTitle,
  totalMinutes,
  type InsertOptions,
} from './blocks';
export {
  addHomeworkQuiz,
  setHomeworkInteraction,
  addHomeworkReading,
  addHomeworkWriting,
  addHomeworkVoice,
  asideMeta,
  removeHomeworkTask,
  setHomework,
  setHomeworkTask,
  setRecap,
} from './asides';
export { setInteraction } from './interaction';
export {
  addHtmlElement,
  addIframeElement,
  addImageElement,
  addMarkdownElement,
  addPdfElement,
  addTextElement,
  applyPictureTarget,
  clearElementStyling,
  removeElement,
  removeMedia,
  setElementAlign,
  setElementBox,
  setElementHtml,
  setElementIframe,
  setElementImage,
  setElementMarkdown,
  setElementPdf,
  setElementSpans,
  setElementText,
  styleElementRange,
  setMedia,
  setMediaAspect,
  setMediaFocal,
  setMediaPlace,
  setMediaSize,
  stepMedia,
  withMediaAspect,
  withMediaFocal,
  withMediaPlace,
  withMediaSize,
  type PictureTarget,
} from './media-elements';
export {
  ELEMENT_LAYOUTS,
  applyElementLayout,
  elementLayoutsFor,
  type ElementLayout,
} from './element-layouts';
export {
  clearPartStyling,
  partFont,
  partFontOnly,
  partSpanCapable,
  partSpans,
  retargetSlotSpans,
  setPartFont,
  stylePartRange,
} from './slot-spans';
export {
  materialIndex,
  optionsFor,
  partEditable,
  partLabel,
  partText,
  promptFontFor,
  promptFor,
  promptSpansFor,
  setPartText,
  setTutorNotes,
} from './parts';
export {
  addListItem,
  canAddListItem,
  canRemoveListItem,
  insertGapAtRange,
  optionCorrect,
  removeListItem,
  setFillTheGapsBank,
  setGapAnswers,
  setGapDistractors,
  setOptionCorrect,
} from './lists';

export { renameDeck } from './asides';
export { setDeckDesign, setSlideDesign, applyBrandKit } from './design';
export { insertTemplate, insertWorkshop, resetTemplateFormatting } from './templates';
export { insertCorrection } from './corrections';
export { insertPracticeExercise, addPracticeHomework } from './practice';
